# Generated by Django 4.2.1 on 2023-06-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-title']},
        ),
    ]
